# Generated by Django 4.2.10 on 2025-03-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('resource_type', models.CharField(choices=[('GITHUB', 'GitHub Repository'), ('PAPER', 'Research Paper'), ('COURSE', 'Online Course'), ('BLOG', 'Blog Post'), ('COMMUNITY', 'Community Resource'), ('DOCUMENTATION', 'Documentation'), ('BOOK', 'Book')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('is_bookmarked', models.BooleanField(default=True)),
                ('is_admin_saved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
