# Generated by Django 4.2.10 on 2025-03-01 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmark',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='resource_type',
            field=models.CharField(choices=[('GITHUB', 'GitHub Repository'), ('PAPER', 'Research Paper')], default='GITHUB', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmark',
            name='source',
            field=models.CharField(default='GitHub', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmark',
            name='title',
            field=models.CharField(default='Untitled Resource', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmark',
            name='url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'url')},
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='resource',
        ),
    ]
