# Generated by Django 4.2.10 on 2025-03-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_alter_bookmark_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='is_admin_saved',
            field=models.BooleanField(default=False),
        ),
    ]
