# Generated by Django 4.2.10 on 2025-03-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0006_alter_bookmark_resource_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
