services:
  - type: web
    name: ai-learning-hub
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ai_learning_hub.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: DATABASE_URL
        fromDatabase:
          name: ai_learning_hub_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false

databases:
  - name: ai_learning_hub_db
    databaseName: ai_learning_hub
    plan: free 