services:
  - type: web
    name: ai-learning-hub
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ai_learning_hub.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: DATABASE_URL
        fromDatabase:
          name: ai_learning_hub_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GITHUB_ACCESS_TOKEN
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
    autoDeploy: true

databases:
  - name: ai_learning_hub_db
    databaseName: ai_learning_hub
    plan: free
    ipAllowList: [] 