# Generated by Django 4.2.10 on 2025-03-13 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('bookmarks', '0001_initial'),
    ]

    operations = []
