# Generated by Django 4.2.10 on 2025-03-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_options_resource_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['title'], name='resources_r_title_25cf8f_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type'], name='resources_r_resourc_1a6f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['created_at'], name='resources_r_created_215cda_idx'),
        ),
    ]
