# Generated by Django 5.1.6 on 2025-03-13 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0009_bookmark_resource_alter_bookmark_user"),
        ("resources", "0004_savedresource"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="bookmarked_by",
            field=models.ManyToManyField(
                related_name="bookmarked_resources_set",
                related_query_name="bookmarked_resource",
                through="bookmarks.Bookmark",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
